// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB8a0UESGgxdRJrwwZVSF_ltyC3SEc2anE',
    appId: '1:424717255720:web:3935d54a42df5f8cfee11d',
    messagingSenderId: '424717255720',
    projectId: 'utc-app-ae5b9',
    authDomain: 'utc-app-ae5b9.firebaseapp.com',
    storageBucket: 'utc-app-ae5b9.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDJKeoxeS1l21DMs1elWwSjAP16GnaXv9o',
    appId: '1:424717255720:android:a330ddc1912495eafee11d',
    messagingSenderId: '424717255720',
    projectId: 'utc-app-ae5b9',
    storageBucket: 'utc-app-ae5b9.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCDaDgRiCtFokFVHuzOQEafaYQdOVRxwB0',
    appId: '1:424717255720:ios:6875eca03d8c02d4fee11d',
    messagingSenderId: '424717255720',
    projectId: 'utc-app-ae5b9',
    storageBucket: 'utc-app-ae5b9.appspot.com',
    iosClientId: '424717255720-bo8fe97athoq75vg14vk1j0pgdu34hlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.utcStudentApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCDaDgRiCtFokFVHuzOQEafaYQdOVRxwB0',
    appId: '1:424717255720:ios:6875eca03d8c02d4fee11d',
    messagingSenderId: '424717255720',
    projectId: 'utc-app-ae5b9',
    storageBucket: 'utc-app-ae5b9.appspot.com',
    iosClientId: '424717255720-bo8fe97athoq75vg14vk1j0pgdu34hlc.apps.googleusercontent.com',
    iosBundleId: 'com.example.utcStudentApp',
  );
}
